package com.usabilityetc.alphaslider;

import java.util.EventObject;

/**
 * AlphaSliderEvent objects are generated by an AlphaSlider
 * when the user changes the value of the slider.
 * 
 * @author Jeffrey Morgan
 */
public class AlphaSliderEvent<T> extends EventObject {
  private static final long serialVersionUID = 252598499080834503L;

  // The value of the AlphaSlider when this object was created
  private T currentValue = null;

  /**
   * Create an AlphaSliderEvent with the specified source AlphaSlider and it's current value.
   * 
   * @param source                 the AlphaSlider that created this event object
   * @param currentValue           the value of the AlphaSlider when it created this event object
   * @throws NullPointerException  if currentValue is null
   */
  public AlphaSliderEvent(final AlphaSlider<T> source, final T currentValue) {
    super(source);
    if (currentValue == null) {
      throw new NullPointerException("currentValue cannot be null");
    }
    this.currentValue = currentValue;
  }

  /**
   * Return the value of the AlphaSlider when it created this event object.
   * 
   * @return The current AlphaSlider value
   */
  public T getCurrentValue() {
    return currentValue;
  }
}
