package com.usabilityetc.alphaslider;

import java.util.EventListener;

/**
 * An AlphaSlider object notifies registered AlphaSliderEventListener
 * objects when the user changes the value of the AlphaSlider.
 */
public interface AlphaSliderEventListener<T> extends EventListener {
  /**
   * Called by the AlphaSlider when the user changes the AlphaSlider's value
   * 
   * @param event  the event generated by the AlphaSlider when the user changes it's value
   */
  public void valueChanged(AlphaSliderEvent<T> event);
}
